{
  "comments": [
    {
      "key": {
        "uuid": "48cbf469_c1549e4c",
        "filename": "/COMMIT_MSG",
        "patchSetId": 8
      },
      "lineNbr": 21,
      "author": {
        "id": 1137063
      },
      "writtenOn": "2020-02-03T18:45:53Z",
      "side": 1,
      "message": "This is the wrong bug number.",
      "range": {
        "startLine": 21,
        "startChar": 0,
        "endLine": 21,
        "endChar": 14
      },
      "revId": "f530c679a0be31f1879c76f263677115f9615de3",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    }
  ]
}